services:
  app:
    build: 
      context: .  # Build context is the current directory
      dockerfile: python.dockerfile  # Specify the Dockerfile for Python app
    volumes:
      - /mnt/movies:/movies
      - /mnt/tv:/series
      - ./python_app:/python_app  
      - ./images:/python_app/static/images
    depends_on:
      - redis
    working_dir: /python_app
    ports:
      - "${APP_PORT}:${APP_PORT}"  # Map container port to host port
    env_file:
      - .secrets
      - .env
    command: gunicorn --config gunicorn_config.py main:app
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1      
  redis: #this must match REDIS_SERVER_NAME
    image: redis:alpine
    ports:
      - "6379:6379"   
    volumes:
      - ./redis-data:/data  # Mount a named volume for persisting data  
    environment:
      REDIS_ARGS: --save 600 1
    working_dir: /data
    restart: unless-stopped

volumes:
  # Additional volumes for shared data
  redis-data:  # Define a named volume for persistence
